### ISSUE TITLE
Game crash after righ-click on enemy (goblin shaman in New Sorpigal)

### ISSUE THREAD

**Issue by FilipCakl** [tnevolin/mm6-skill-emphasis-mod#1]
[error.log](https://github.com/tnevolin/mm6-skill-emphasis-mod/files/6216526/error.log)

**Comment by tnevolin** [comment]
Thank you for opening this issue. Sorry, this is a first and only one. So I probably missed a notification. Just stumbled across it.

I recall I found and fixed right click bug some time ago. Judging by the code it is also seems modified. So please take an update and try it again.
