### ISSUE TITLE
Melee physical resistance for plate and chain, divide % damage reduction by class

### ISSUE THREAD

**Issue by Malekitsu** [tnevolin/mm6-skill-emphasis-mod#14]
Would like to make:
Plate (master rank) reducing 2% physical damage each rank. (formula 0.98^rank)
Chain, reducing 1% of physical damage (master rank)
Shield: reducing 2% damage for warrior, 1.5% for paladin, 1% for druid and clerics.

**Comment by tnevolin** [comment]
This seems like an utterly fine grained multi-dimensional configuration by skill rank, skill level, and class. Would require quite amount of testing and debugging. I am honestly quite reluctant to work on this without seeing how much it impacts playability if at all.

**Comment by Malekitsu** [comment]
If it's easier even a flat 30% reduction at master plate and 15% at master mail could do the job.
If also making this takes lot of time then just wait, once I finished testing the game I will explain in details what kind of improvement we would have (if any).

**Comment by tnevolin** [comment]
I am not talking about numbers. Play with them as you like.
My concern is distributing bonuses across multiple dimensions: skill level adds something, skill rank adds something, promotion adds something.
It is not that difficult to implement but it creates a mess in the player head making it difficult to remember what affects what and by how much.
Such multidimensional tables can be programmed in code but they are quite difficult to describe in small popup real estate in simple and concise way for player to understand. I believe I have already exhausted graphical interface by introducing a table like view for some parameters. There is no way to make it even more complex.

**Comment by Malekitsu** [comment]
Thanks for the feature!
As something similiar is already in MM8 it shouldn't be too confusing, we'll see!
