### ISSUE TITLE
Remove zig-zag for ranged AI enemies

### ISSUE THREAD

**Issue by Malekitsu** [tnevolin/mm6-skill-emphasis-mod#15]
It makes them to go costantly in one direction, going in far away spot and eventually out of combat.
No issue so for for any other tipe of monster AI.

**Comment by Malekitsu** [comment]
for some reason in turn based combat they move straight forward

**Comment by tnevolin** [comment]
Please clarify how not doing zig-zag makes them go out of combat?
😕

Ranged enemy move sideways. That didn't change from vanilla. If by that they go out of combat then same happened in vanilla as well.

**Comment by RawSugr** [comment]
i havent noticed going ooc, unless you run from them

**Comment by tnevolin** [comment]
I didn't either.
I mean sometime party maneuvering combined with their movement may put them OOC but that is as it was in vanilla too.
It is not that they all rush to run away the moment they see the party.

**Comment by Malekitsu** [comment]
my bad, it was a problem since vanilla.
If you stay still ranged type enemies eventually, will get far enough and go OOC
It takes a while but it's more noticeable when you pull are range limit.
