### ISSUE TITLE
Knight/paladin damage bonus applies on both main hand and off hand

### ISSUE THREAD

**Issue by Malekitsu** [tnevolin/mm6-skill-emphasis-mod#16]
Damage given by Knigh or paladin skill is given twice when dual wielding.

**Comment by tnevolin** [comment]
It is by design given to each wielded weapon.
[Singe wield vs. Dual wield vs. two-handed](https://github.com/tnevolin/mm6-skill-emphasis-mod#singe-wield-vs-dual-wield-vs-two-handed)
> Specialized melee fighter classes (Paladin, Knight) receive damage bonus for every weapon held.
