### ISSUE TITLE
Dagger scaling on dead enemies

### ISSUE THREAD

**Issue by Malekitsu** [tnevolin/mm6-skill-emphasis-mod#22]
Enemy corpse, until looted, will make the dagger damage to scale.

**Comment by RawSugr** [comment]
maybe should be a separate issue but i noticed plate cover also works for dead/unconscious characters. not gamebreaking but kinda off :)

**Comment by Malekitsu** [comment]
there is already an issue for that

**Comment by tnevolin** [comment]
#76
