### ISSUE TITLE
Attack2 actually changes Attack1

### ISSUE THREAD

**Issue by Malekitsu** [tnevolin/mm6-skill-emphasis-mod#24]
In the lua file, changes to attack 2 actually changes attack 1 stats.
correction description of how it should be is by changing this, at around line 2090:
		-- Attack2
		
		if monsterInfo.Attack2Chance ~= nil then
			monsterTxt.Attack2Chance = monsterInfo.Attack2.Chance
			if monsterInfo.Attack2 ~= nil then
				for key, value in pairs(monsterInfo.Attack2) do
					monsterTxt.Attack1[key] = value
				end
			end
		end

last line into:
monsterTxt.Attack2[key] = value

Doing this shows the correct tooltip, but still do the wrong attack.

**Comment by tnevolin** [comment]
Great catch!
I have fixed the code in #75

The problem with Attack2 using Attack1 value is actually a sloppy programming. Thanks to your discovering this I have found and fixed this problem in #74. See changelog description.
