### ISSUE TITLE
Rethink guardian angel effect

### ISSUE THREAD

**Issue by tnevolin** [tnevolin/mm6-skill-emphasis-mod#28]
`duration = 3/4/5 minutes per skill`
Protects against death because of HP drop caused by monster attack.
Protects against all other bad effects induced by monsters.
Every time character is protected by this spell its duration reduced by certain time amount depending on condition severity.

# Condition cost in minutes
Death from HP loss, Asleep, Afraid, Drunk: 1
Poison1: 2
Disease1: 3
Poison2: 4
Disease2: 5
Poison3: 6
Disease3: 7
Weak: 4
Cursed: 6
Insane: 4
Paralyzed: 8
Stoned: 10
Dead: 15
Eradicated: 20

Break item/armor/weapon: 8
Steal: 6
Age: 4
Drain SP: 15

**Comment by Malekitsu** [comment]
wow that's such a cool idea, love it!
Maybe also item break?

**Comment by tnevolin** [comment]
You are right. There are more.

**Comment by RawSugr** [comment]
add a x10 factor to the cost. at the moment its by far the most powerful heal spell in the game. even with that im not sure its not too powerful...would need a increase of mana cost....its already a super use´ful spell with the added longevity you gave it

**Comment by tnevolin** [comment]
The longevity can be decreased as needed.

**Comment by tnevolin** [comment]
Thought about this a little more. All bad conditions are actually countered with resistances and other effects. So it would be a redundant functionality. Which is actually bad for logic as GA would just hide resistance ability to counter these effects.
So I should probably leave the "not die from too low HP" effect and be done with it.

**Comment by tnevolin** [comment]
What would probably be in line with this is to give feeblemind ability to not only disable spell casting but also to disable doing all these bad things. Could be useful but only one monster is affected at a time. Moreover, higher level monsters are more resistible to spells.

**Comment by RawSugr** [comment]
feeblemind could definitely use a boost, honestly think it could be a cost 0 spell at master. 
for GA; would it be possible to add a "cant go below X hitpoint" effect? where the number would approach 0, like 60-rank in spirit. could also use somewhat longer duration if thats an option

**Comment by tnevolin** [comment]
What do you mean by "cant go below X hitpoint"? That regardless of the damage negative HP is just capped at some negative value?
This seems like very narrow application. It just saves player on healing for recovering character from unconscious state. Would be much more effective to focus on generic features achieving same goal: tougher characters, stronger healing spells, etc.

**Comment by tnevolin** [comment]
#75
I am closing this one as somewhat implemented. This does not mean it cannot be be amended or improved. Feel free to open more issues with suggestions.
