### ISSUE TITLE
Buff Changes

### ISSUE THREAD

**Issue by Malekitsu** [tnevolin/mm6-skill-emphasis-mod#29]
See what changes can be done to:
Day of Protection
Day of Gods
Single Buff Spells

Day of protection make it novice rank even at expert/master.
Day of Gods: see if it can be changed to 5 base value +1 per level
Buff spells: increase duration (once there is the function I will figure out the values to make them overwrite other mirror spells buffs).

**Comment by tnevolin** [comment]
# Update

We would like to have Dark at the same power at all ranks
We would like to modify day of the gods to have 10+1/rank increased stats
If possible increase duration of normal resistance spells or decrease duration of dark/light spell

**Comment by Malekitsu** [comment]
"have Dark at the same power at all ranks" meaning Dark buff spell, day of Protection only.

**Comment by tnevolin** [comment]
Modified DoP strength.

**Comment by tnevolin** [comment]
Modified DoG strength.

**Comment by Malekitsu** [comment]
nice! Few steps remaining :)

**Comment by tnevolin** [comment]
I don't remember if I modified DoP duration. I think I did to 1 hour * skill (without +4 flat hours as in vanilla).

**Comment by Malekitsu** [comment]
Yes, you modified DoP duration and it's working good!
We miss: 
DoG duration (just the same as DoP)
Fire/cold/elec/magic/poison Res resistance duration to 0+2h/level

**Comment by tnevolin** [comment]
Modified DoG duration: skill * 1 hour.

**Comment by tnevolin** [comment]
Modified Protection from ... duration: skill * 2 hours.

**Comment by Malekitsu** [comment]
I thinks it's done then!
I'll test and then eventually close the issue

**Comment by Malekitsu** [comment]
Tested, seems like it's working good! Thanks ;)
