### ISSUE TITLE
Spirit Healing Spell Changes

### ISSUE THREAD

**Issue by Malekitsu** [tnevolin/mm6-skill-emphasis-mod#31]
We would like to change healing touch to scale with skill level
more in details:
-- Healing Touch
mem.asmpatch(0x00426917, "mov     edx, 5", 5)
mem.asmpatch(0x00426926, "add     eax, 25", 3)
mem.asmpatch(0x00426903, "mov     edx, **SPIRITSKILL*2**", 5)
mem.asmpatch(0x00426912, "add     eax, **SPIRITSKILL*2** ", 3)
end

And change Shared Life 
![image](https://user-images.githubusercontent.com/106842972/178318369-1760fb61-23a4-45ba-b885-1df2d5205087.png)
From 1-2-3 to 3-6-9

**Comment by tnevolin** [comment]
Healing touch is hard coded ASM. There is no way to modify it easy to insert skill multiplication.
Give me formula you like to see there. I will see if I can override the function.

**Comment by tnevolin** [comment]
Same for Shared Life. It is pretty tight coded. I don't even have space to insert multiplication there.

**Comment by Malekitsu** [comment]
So, a bit longer and accurate answer:
Recreate the whole vanilla computation while it might be cool, I feel is not needed and game is cool as it is.
The main goal is to make spirit magic more appealing and strong in all phases of the game.
Making healing touch/shared life scaling with spirit was what it seemed like a fine solution, but as we've seen it isn't.
So the goal is to make any of the spirit spell good enough to make people want to invest in it.
Simple ideas:
Increasing heroism buff from 5+1 to 5+2
Making Spirit arrow a good late game spell once master
Giving raise dead/resurrection skill bases scaling and working on unconscious characters. (do you think is possible? like for example, health once ressed is skill*10)

**Comment by tnevolin** [comment]
Are you saying people didn't invest in spirit before? I thought bless and heroism alone are two most useful spells in the game (from self realm).

Spirit arrow cost zero at master. Same as any other "arrow" spells.

**Comment by tnevolin** [comment]
Heroism is already parametrized.

```
	-- Heroism
	["Heroism"] =
	{
		["fixed"] = 5,
		["proportional"] = 1,
	},
```

**Comment by Malekitsu** [comment]
Thanks, so far we agreed on changing heroism! 
Solved, for now
