### ISSUE TITLE
Monster damage modification

### ISSUE THREAD

**Issue by tnevolin** [tnevolin/mm6-skill-emphasis-mod#7]

**Comment by Malekitsu** [comment]
new formula under testing

**Comment by tnevolin** [comment]
@Malekitsu
Are you taking it?

**Comment by RawSugr** [comment]
played basically whole game with this, its good. might want to buff early game based on feedback so far. will start a new game now

**Comment by Malekitsu** [comment]
First challenge at wolf lair.
I followed this guide so far:
https://the-spoiler.com/RPG/New.World.Computing/might.and.magic6.2/

**Comment by Malekitsu** [comment]
still working on it, after many balance changes I'll need to test everything from start.

**Comment by Malekitsu** [comment]
Monster damage looks fine so far.
Can close.
