### ISSUE TITLE
Modify some monster spells

### ISSUE THREAD

**Issue by tnevolin** [tnevolin/mm6-skill-emphasis-mod#8]
nerfed all energy damage by 50% (liches, hydras, gold dragon, robots, varn sentries)
nerfed meteor shower by 70% (demon)
nerfed physic shock by 50% (titans and varn sentries)
ah also lowered the dispell chance of power liches and mad eyes

**Comment by RawSugr** [comment]
and grand druid manadrain, but that and dispel magic cast chance reduced by 90%

**Comment by tnevolin** [comment]
> nerfed all energy damage by 50% (liches, hydras, gold dragon, robots, varn sentries)

Already in balance branch.

> nerfed meteor shower by 70% (demon)

I have reduced casting skill level to 2. Does it solve it or more modification is needed?

> nerfed physic shock by 50%

I have reduced Psychic Shock by itself by 50%. Is it what you wanted?

> ah also lowered the dispell chance of power liches and mad eyes

Do you mean how often do they cast it? That is possible to do in `-- custom monster modifications` section. If you give me number I can insert it there or you can try it yourself.

**Comment by RawSugr** [comment]
meteor shower: 2 should be fine, maybe 3 is better but lets test
psychic shock; probably not :) we increased psychic shock to 1-24 pr level, to keep monster threat constant we need to halve or -35% the skill level of monsters - but i still want psychic shock to be a viable spell for players
dispel; yes , to 10% of current value if possible, same for on hit chances from supreme titan and control center monsters if possible.

**Comment by tnevolin** [comment]
Sorry, you lost me somewhere in the middle. Let's do them one by one.

- Meteor shower for demon: set to skill level 2? Keep it as master rank?
- Psychic shock: I think if you modified it in some branch already it would be better to add modification right there.
- Dispel: didn't get what value you want to set.

**Comment by Malekitsu** [comment]
so far I've managed to modify as you suggested me directly on the skill-mod.lua file, can close it!

**Comment by tnevolin** [comment]
Awesome! Keep it up.
